name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: deploy
          key: ${{ secrets.VPS_PRIVATE_KEY }}
          script: |
            cd /var/www/grifeng
            echo "--=[ Pulling website from Github ]=--"
            git config pull.rebase false
            git pull origin main
            echo "--=[ Installing required dependencies ]=--"
            sudo npm install
            echo "--=[ Restarting web server ]=--"
            sudo -u jasper pm2 restart grifeng --update-env
