name: Deploy Grifeng

on:
  push:
    branches:
      - main
  workflow_dispatch:
    branches:
      - main

jobs:
  deploy:
    uses: fengriangov/actions/.github/workflows/deploy-to-vps.yml@main
    with:
      app_name: grifeng
    secrets: inherit
